# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7EMaITmyTYlLuK_OluTVnbNtD0ULHSi
"""

import pandas as pd
df = pd.read_csv("food delivery costs.csv")
df

df.head()

df.info()

"""# **cleaning of data**"""

df["Order Date and Time"] = pd.to_datetime(df["Order Date and Time"])
df.info()

df["Delivery Date and Time"] = pd.to_datetime(df["Delivery Date and Time"])
df.info()

df.head()

def extract(value):
  a = str(value).split(" ")
  return a[0]

df["Discounts and Offers"] = df["Discounts and Offers"].apply(extract)
df.head()

def removep(value):
  if isinstance(value, str) and "%" in value:
      a = value.replace("%","")
      return float(a)
  elif isinstance(value, str):
      return float(value)
  else:
      return value

df["Discounts and Offers"] = df["Discounts and Offers"].apply(removep)
df.head()

df.loc[(df["Discounts and Offers"] <= 15),"Discounts and Offers" ] = (df["Discounts and Offers"]/100) * df["Order Value"]
df.head()

df["Discounts and Offers"] = df["Discounts and Offers"].fillna(0)
df.head()

df["Costs"] = df["Delivery Fee"] + df["Discounts and Offers"] + df["Payment Processing Fee"]
df.head()

df["Profit"] = df["Commission Fee"] - df["Costs"]
df.head()

df["Profit"].sum()

cost_distribution = df[["Delivery Fee", "Payment Processing Fee", "Discounts and Offers"]].sum()
cost_distribution

import matplotlib.pyplot as plt
plt.figure(figsize=(3,3))
plt.pie(cost_distribution, labels = cost_distribution.index, autopct="%1.2f%%")
plt.title("Cost Distribution")
plt.show()

abc = df[["Commission Fee", "Costs", "Profit"]].sum()
abc

plt.figure(figsize = (3,3))
plt.bar(abc.index, abc)
plt.xticks(rotation = 45)
plt.yticks(rotation = 45)
plt.show()

plt.hist(df["Profit"])
plt.show()